islands-router: document button-text hydration-error
doesn't persist without component erasure and `islands-router` flags.

this started with:
61571ed2 (https://github.com/leptos-rs/leptos/issues/4443)

cc:
- https://github.com/leptos-rs/leptos/issues/3936
- https://github.com/leptos-rs/leptos/issues/4831

```
Error: expect(locator).toHaveText(expected) failed

    Locator:  locator('button[class=counter]')
    Expected: "Click Me: 1"
    Received: "Click Me: 0"
    Timeout:  5000ms

    Call log:
      - Expect "toHaveText" with timeout 5000ms
      - waiting for locator('button[class=counter]')
        14 × locator resolved to <button class="counter">…</button>
           - unexpected value "Click Me: 0"

      36 |   await expect(page.locator("button[class=counter]")).toHaveText("Click Me: 0");
      37 |   await page.click('button[class=counter]'); // 5
    > 38 |   await expect(page.locator("button[class=counter]")).toHaveText("Click Me: 1");
         |                                                       ^
      39 |
      40 |   expect(errors).toEqual([]);
      41 | });
```

```
A hydration error occurred while trying to hydrate an element defined at src/app.rs:214:10.

The framework expected a text node, but found this instead:  <!---->
```

(`src/app.rs:214:10` being the counter view)

```
<button class="counter">
  <!--bo-TypeId(0x7885a517f6c704f34eb6d2bfe6f4b10f)-->
  <!--bo-TypeId(0x3239c2d3a0977df033859f8b35e760ce)-->
  "Click Me: "
  <!--bc-TypeId(0x3239c2d3a0977df033859f8b35e760ce)-->
  <!--bo-TypeId(0x919b61842e0df2fe45f055fd033a104b)-->
  0
  <!--bc-TypeId(0x919b61842e0df2fe45f055fd033a104b)-->
  <!----> <-- here
  <!--bc-TypeId(0x7885a517f6c704f34eb6d2bfe6f4b10f)-->
  <!---->
</button>
```